[workspace]
members = ["dprint_plugin", "markup_fmt"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0"
insta = { version = "1.44", features = ["glob"] }
similar-asserts = "1.7"
toml = "0.9"

[profile.release]
lto = true
opt-level = "s"
strip = "debuginfo"
